#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen2/modular_qwen2.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen2.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

"""
ZLLM (LLMHips-LM) 核心模型实现
================================
本文件包含 LLMHips-LM 的全部 PyTorch 模型类，按从底到顶的层次结构组织：

  Qwen2MLP               ← 前馈网络（FFN），实现 SwiGLU 门控激活
  Qwen2RMSNorm           ← RMS 归一化层，替代 LayerNorm
  Qwen2RotaryEmbedding   ← 旋转位置编码（RoPE）计算模块
  Qwen2Attention         ← 多头注意力（支持 GQA / SWA）
  Qwen2DecoderLayer      ← 单层 Transformer 解码器块（注意力 + FFN + 残差）
  Qwen2Model             ← 裸模型：Embedding + N × DecoderLayer + 最终 Norm
  Qwen2ForCausalLM       ← 因果语言模型头：Qwen2Model + lm_head（输出 logits）
  Qwen2ForSequenceClassification  ← 序列分类头
  Qwen2ForTokenClassification     ← Token 分类头
  Qwen2ForQuestionAnswering        ← 问答头

推理流程（以 Qwen2ForCausalLM 为例）：
  input_ids
    → embed_tokens（查词表得到 token 向量）
    → rotary_emb（计算 cos/sin 位置编码）
    → ×N DecoderLayer（注意力 + FFN + 残差 + 归一化）
    → norm（最终 RMSNorm）
    → lm_head（线性映射到词表维度，得到每个位置的 logits）
    → softmax / argmax（解码出下一个 token）
"""

from typing import Callable, Optional, Union

import torch
from torch import nn

# ACT2FN：激活函数注册表，通过字符串名称（如 "silu"）查找对应的函数对象
from ...activations import ACT2FN

# Cache / DynamicCache：KV Cache 的抽象基类与动态实现
# KV Cache 在自回归推理时缓存每层的 Key/Value，避免重复计算历史 token 的注意力
from ...cache_utils import Cache, DynamicCache

# GenerationMixin：提供 .generate() 方法（贪心解码、束搜索、采样等）
from ...generation import GenerationMixin

# use_kernel_forward_from_hub：装饰器，允许从 Hub 加载高效 CUDA 自定义算子（如 Triton kernel）
from ...integrations import use_kernel_forward_from_hub

# create_causal_mask：构造因果掩码（下三角矩阵），防止 token 看到未来信息
# create_sliding_window_causal_mask：构造带滑动窗口的因果掩码
from ...masking_utils import create_causal_mask, create_sliding_window_causal_mask

# FlashAttentionKwargs：Flash Attention 2 专用的额外关键字参数类型定义
from ...modeling_flash_attention_utils import FlashAttentionKwargs

# Generic*：通用的任务头实现，Qwen2 直接继承而不需要额外实现
from ...modeling_layers import (
    GenericForQuestionAnswering,
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,  # 支持梯度检查点（用显存换计算，训练大模型时常用）
)

# 模型输出数据类：包含 last_hidden_state / past_key_values / logits 等字段
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast

# ROPE_INIT_FUNCTIONS：各种 RoPE 变体的初始化函数注册表
# dynamic_rope_update：装饰器，在生成时动态更新 RoPE 的 inv_freq（支持外推）
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update

# ALL_ATTENTION_FUNCTIONS：注意力后端注册表（eager / flash_attention_2 / sdpa 等）
# PreTrainedModel：HuggingFace 所有预训练模型的基类
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel

# Unpack：用于 TypedDict 类型解包的类型注解工具
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple
from ...utils.deprecation import deprecate_kwarg
from ...utils.generic import check_model_inputs

# 本包的配置类
from .configuration_qwen2 import Qwen2Config


# ══════════════════════════════════════════════════════════════════════════════
# 前馈网络（FFN / MLP）—— SwiGLU 门控激活结构
# ══════════════════════════════════════════════════════════════════════════════

class Qwen2MLP(nn.Module):
    """
    SwiGLU 门控前馈网络（Feed-Forward Network）。

    传统 FFN：FFN(x) = W₂ · ReLU(W₁ · x)

    SwiGLU 变体（本实现）：
        gate = SiLU(gate_proj(x))    # 门控信号：经过激活函数的非线性变换
        up   = up_proj(x)            # 值信号：线性变换，不经过激活
        FFN(x) = down_proj(gate * up)  # 逐元素相乘后投影回隐藏维度

    为什么用 SwiGLU？
    - SiLU（= x·σ(x)）比 ReLU 更平滑，梯度不会在负值区域完全消失
    - 门控机制（gate * up）让网络能够自适应地过滤信息，提升表达能力
    - 实验表明 SwiGLU 在大语言模型上效果优于 GeLU / ReLU

    参数量：
        gate_proj: hidden_size × intermediate_size（无 bias）
        up_proj:   hidden_size × intermediate_size（无 bias）
        down_proj: intermediate_size × hidden_size（无 bias）
    """

    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size           # 输入/输出维度 d_model
        self.intermediate_size = config.intermediate_size  # FFN 中间层维度 d_ffn

        # gate_proj：计算门控信号，输出经过激活函数
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        # up_proj：计算值信号，输出不经过激活函数
        self.up_proj   = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        # down_proj：将中间层维度压缩回隐藏层维度
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)

        # act_fn：通过配置字符串（如 "silu"）查找对应的激活函数
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        # SwiGLU 计算：act(gate_proj(x)) ⊙ up_proj(x)，再投影回 hidden_size
        # ⊙ 表示逐元素乘法（Hadamard 积）
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


# ══════════════════════════════════════════════════════════════════════════════
# 旋转位置编码（RoPE）辅助函数
# ══════════════════════════════════════════════════════════════════════════════

def rotate_half(x):
    """
    将向量后半段取反并前移，用于构造旋转矩阵的等效操作。

    RoPE 的核心思想：用旋转矩阵 R(θ) 编码位置信息。
    对于二维向量 [x1, x2]，旋转 θ 角后得到：
        [x1·cos(θ) - x2·sin(θ),  x1·sin(θ) + x2·cos(θ)]

    对高维向量，将其视为若干二维子空间的组合，分别旋转：
        rotate_half(x) = [-x2, x1]（即后半取负，与前半交换位置）
        q_rotated = q * cos + rotate_half(q) * sin

    这样做避免了显式构造和存储 d×d 的旋转矩阵，计算高效。

    输入: x  shape [..., d]，其中 d 为偶数
    输出: [-x[d/2:], x[:d/2]] 拼接后的张量，shape 不变
    """
    x1 = x[..., : x.shape[-1] // 2]   # 前半部分
    x2 = x[..., x.shape[-1] // 2 :]   # 后半部分
    return torch.cat((-x2, x1), dim=-1)  # 后半取负后拼到前面


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """
    将旋转位置编码（RoPE）应用到 Query 和 Key 张量上。

    RoPE 的关键性质：
        <RoPE(q, m), RoPE(k, n)> 只与 (m - n) 有关，即内积只依赖相对位置
    这使得 RoPE 天然支持相对位置感知，且可以外推到训练长度以外的序列。

    参数：
        q   (Tensor): Query 张量，shape [batch, heads, seq, head_dim]
        k   (Tensor): Key   张量，shape [batch, kv_heads, seq, head_dim]
        cos (Tensor): RoPE cos 分量，由 Qwen2RotaryEmbedding 计算
        sin (Tensor): RoPE sin 分量，由 Qwen2RotaryEmbedding 计算
        position_ids: 已废弃参数，保留仅为 API 兼容
        unsqueeze_dim: 在哪个维度插入 head 维度以便广播
            - q/k shape [batch, heads, seq, dim] → unsqueeze_dim=1（在 heads 前插入）

    返回：
        q_embed, k_embed：应用 RoPE 后的 Q/K 张量
    """
    # 在 head 维度插入维度，使 cos/sin 可以广播到每个注意力头
    cos = cos.unsqueeze(unsqueeze_dim)  # [batch, 1, seq, head_dim]
    sin = sin.unsqueeze(unsqueeze_dim)

    # 旋转公式：q_embed = q * cos + rotate_half(q) * sin
    # 等价于对 q 的每个二维子空间执行旋转变换
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


# ══════════════════════════════════════════════════════════════════════════════
# GQA 辅助函数：KV 头数扩展
# ══════════════════════════════════════════════════════════════════════════════

def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    将 KV 头数扩展为与 Q 头数一致，用于 GQA（分组查询注意力）的标准注意力计算。

    GQA 原理：
        - Q 有 num_attention_heads 个头（如 28）
        - K/V 只有 num_key_value_heads 个头（如 4）
        - 每 (28/4=7) 个 Q 头共享同一组 K/V

    在使用标准的 torch.matmul 计算注意力时，需要先把 K/V 复制展开，
    使其头数与 Q 一致，才能做批量矩阵乘法。

    注意：这里的复制是内存共享的（expand 不分配新内存），
         只在 reshape 时才真正占用内存，相对高效。

    输入：
        hidden_states: shape [batch, num_key_value_heads, seq, head_dim]
        n_rep: 每个 KV 头被 n_rep 个 Q 头共享

    输出：
        shape [batch, num_attention_heads, seq, head_dim]
          （num_attention_heads = num_key_value_heads × n_rep）
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        # MHA 情况下 Q/K/V 头数相同，无需复制
        return hidden_states
    # expand：在第 2 维（None 维）重复 n_rep 次（不分配新内存）
    hidden_states = hidden_states[:, :, None, :, :].expand(
        batch, num_key_value_heads, n_rep, slen, head_dim
    )
    # reshape 合并 num_key_value_heads × n_rep → num_attention_heads
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


# ══════════════════════════════════════════════════════════════════════════════
# 标准（Eager）注意力计算实现
# ══════════════════════════════════════════════════════════════════════════════

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    """
    标准的 Scaled Dot-Product Attention 实现（不使用 Flash Attention）。

    计算公式：
        Attention(Q, K, V) = softmax(Q·Kᵀ / √d_k + mask) · V

    步骤：
        1. 将 KV 头数扩展至与 Q 一致（GQA 兼容）
        2. 计算注意力分数矩阵 Q·Kᵀ，并缩放（防止点积过大导致 softmax 梯度消失）
        3. 加上因果掩码（-inf 使未来位置的 softmax 输出趋近 0）
        4. Softmax 归一化得到注意力权重
        5. Dropout 正则化（训练时）
        6. 加权求和 Value，得到上下文向量

    参数：
        module  : 调用方的 Qwen2Attention 实例（用于获取 num_key_value_groups 等属性）
        query   : [batch, q_heads, seq, head_dim]
        key     : [batch, kv_heads, seq, head_dim]
        value   : [batch, kv_heads, seq, head_dim]
        attention_mask: [batch, 1, seq, seq] 的加性掩码（0 或 -inf）
        scaling : 缩放因子，通常为 1/√head_dim
        dropout : 注意力 Dropout 比例

    返回：
        attn_output : [batch, seq, q_heads, head_dim]（转置后）
        attn_weights: [batch, q_heads, q_seq, k_seq]（注意力权重，可用于可视化）
    """
    # GQA：将 KV 复制展开，使头数与 Q 一致
    key_states   = repeat_kv(key,   module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    # ── 计算注意力分数 ──
    # [batch, heads, q_seq, k_seq] = [batch, heads, q_seq, d] × [batch, heads, d, k_seq]
    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling

    # 应用因果掩码（只取 key 序列长度对应的列，兼容 KV Cache 场景）
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask  # 加性掩码（-inf 位置 softmax 后≈0）

    # ── Softmax 归一化 ──
    # 用 float32 计算 softmax 防止数值溢出，之后转回原始精度（如 float16）
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)

    # ── Dropout（仅训练时生效）──
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)

    # ── 加权求和 Value ──
    # [batch, heads, q_seq, k_seq] × [batch, heads, k_seq, d] → [batch, heads, q_seq, d]
    attn_output = torch.matmul(attn_weights, value_states)

    # transpose: [batch, heads, seq, d] → [batch, seq, heads, d]
    # contiguous: 确保内存连续，后续 reshape 才安全
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


# ══════════════════════════════════════════════════════════════════════════════
# 多头注意力层（支持 GQA + RoPE + SWA + KV Cache）
# ══════════════════════════════════════════════════════════════════════════════

class Qwen2Attention(nn.Module):
    """
    多头自注意力层，实现论文 'Attention Is All You Need' 的核心机制，
    并加入以下改进：

    1. GQA（分组查询注意力）：
       Q 有 num_attention_heads 个头，K/V 只有 num_key_value_heads 个头，
       多个 Q 头共享同一 K/V，减少 KV Cache 显存占用。

    2. RoPE（旋转位置编码）：
       在计算注意力前对 Q/K 施加旋转变换，将绝对位置信息编码为相对位置感知。

    3. 滑动窗口注意力（SWA，可选）：
       通过 sliding_window 限制每个 token 只关注最近 W 个 token，
       将注意力复杂度从 O(n²) 降至 O(n·W)，适合处理长序列。

    4. KV Cache：
       推理时缓存历史 token 的 K/V，每步只计算新 token，避免重复计算。

    线性投影层：
        q_proj: hidden → num_heads × head_dim   （带 bias）
        k_proj: hidden → kv_heads × head_dim    （带 bias）
        v_proj: hidden → kv_heads × head_dim    （带 bias）
        o_proj: num_heads × head_dim → hidden   （无 bias）

    注意：Q/K/V 投影带 bias，O 投影不带 bias，这是 Qwen2 与 LLaMA 的区别之一。
    """

    def __init__(self, config: Qwen2Config, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx  # 当前层索引，用于 KV Cache 的分层存储

        # 每个注意力头的维度（通常 = hidden_size // num_attention_heads）
        # getattr 提供向后兼容：允许 config 中直接指定 head_dim
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)

        # GQA 分组数：每组有多少个 Q 头共享同一 KV 头
        # 例如：num_attention_heads=28, num_key_value_heads=4 → groups=7
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads

        # 注意力分数缩放因子：1/√head_dim，防止大维度时点积过大
        self.scaling = self.head_dim ** -0.5

        self.attention_dropout = config.attention_dropout

        # 因果注意力（下三角掩码），确保位置 i 只能看到位置 0..i
        self.is_causal = True

        # ── Q/K/V/O 线性投影层 ──
        # Q：将 hidden 映射到所有 Q 头（num_attention_heads 个头）
        self.q_proj = nn.Linear(config.hidden_size, config.num_attention_heads * self.head_dim, bias=True)
        # K：将 hidden 映射到 KV 头（GQA 时头数更少）
        self.k_proj = nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=True)
        # V：同 K
        self.v_proj = nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=True)
        # O：将多头输出拼接后投影回 hidden_size（无 bias）
        self.o_proj = nn.Linear(config.num_attention_heads * self.head_dim, config.hidden_size, bias=False)

        # 滑动窗口大小：仅当该层被配置为 "sliding_attention" 时才有效
        self.sliding_window = (
            config.sliding_window
            if config.layer_types[layer_idx] == "sliding_attention"
            else None
        )

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],  # (cos, sin)
        attention_mask: Optional[torch.Tensor],
        past_key_values: Optional[Cache] = None,   # KV Cache
        cache_position: Optional[torch.LongTensor] = None,  # 当前生成位置的索引
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        """
        注意力层前向传播。

        参数：
            hidden_states   : [batch, seq, hidden_size] 上一层的输出
            position_embeddings : (cos, sin) RoPE 位置编码，由 Qwen2RotaryEmbedding 提前计算
            attention_mask  : 因果掩码，shape [batch, 1, seq, seq]
            past_key_values : KV Cache 对象，推理加速用
            cache_position  : 当前生成 token 在序列中的绝对位置索引

        返回：
            attn_output : [batch, seq, hidden_size] 注意力层输出
            attn_weights: 注意力权重（用于调试/可视化，非必要时为 None）
        """
        # input_shape: [batch, seq]
        # hidden_shape: [batch, seq, num_heads, head_dim]（用于 view reshape）
        input_shape  = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        # ── 线性投影 + reshape 为多头格式 ──
        # [batch, seq, hidden] → [batch, seq, heads, head_dim] → [batch, heads, seq, head_dim]
        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states   = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        # ── 应用旋转位置编码到 Q 和 K ──
        # V 不需要 RoPE，因为 RoPE 的目的是让注意力分数感知相对位置，
        # 而 V 是加权求和的"值"，不参与位置相关的点积计算
        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        # ── 更新 KV Cache ──
        # past_key_values.update() 将当前步的 K/V 追加到缓存中，
        # 并返回包含历史所有 token 的完整 K/V（用于后续注意力计算）
        if past_key_values is not None:
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_values.update(
                key_states, value_states, self.layer_idx, cache_kwargs
            )

        # ── 选择注意力计算后端 ──
        # eager：标准 PyTorch 实现（本文件中的 eager_attention_forward）
        # flash_attention_2：Flash Attention，显存高效，速度快，需要特定 GPU
        # sdpa：PyTorch 2.0+ 内置的 Scaled Dot-Product Attention（自动选择最优实现）
        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            sliding_window=self.sliding_window,   # SWA 窗口大小（None 表示不使用）
            **kwargs,
        )

        # ── 整合多头输出 ──
        # [batch, seq, heads, head_dim] → [batch, seq, heads×head_dim]
        attn_output = attn_output.reshape(*input_shape, -1).contiguous()

        # ── 输出线性投影 ──
        # [batch, seq, heads×head_dim] → [batch, seq, hidden_size]
        attn_output = self.o_proj(attn_output)

        return attn_output, attn_weights


# ══════════════════════════════════════════════════════════════════════════════
# RMS 归一化层
# ══════════════════════════════════════════════════════════════════════════════

@use_kernel_forward_from_hub("RMSNorm")  # 尝试从 Hub 加载更快的 Triton/CUDA 实现
class Qwen2RMSNorm(nn.Module):
    """
    Root Mean Square Layer Normalization（RMS 归一化）。

    公式：RMSNorm(x) = x / RMS(x) × γ
         其中 RMS(x) = √(mean(x²) + ε)，γ 为可学习的缩放参数

    与 LayerNorm 的区别：
    - LayerNorm：先减去均值（中心化），再除以标准差
    - RMSNorm：只除以 RMS（无中心化步骤）

    为什么用 RMSNorm？
    1. 减少了均值计算，推理速度更快（约快 7-15%）
    2. 实验表明中心化对 Transformer 的性能提升有限，去掉影响不大
    3. 等价于对幅度进行归一化，保留了方向信息

    参数：
        hidden_size : 归一化的最后一维大小（即 d_model）
        eps         : 数值稳定项，防止除以 0
    """

    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        super().__init__()
        # γ：可学习的缩放参数，初始化为全 1（即初始不改变分布）
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps  # ε，防止 RMS 为 0 时数值不稳定

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        # ── 保存原始数据类型（可能是 float16/bfloat16）──
        input_dtype = hidden_states.dtype

        # ── 升精度到 float32 计算方差 ──
        # float16 的精度有限，直接在 fp16 下计算平方均值容易溢出或精度损失
        hidden_states = hidden_states.to(torch.float32)

        # ── 计算 RMS 的倒数：rsqrt(mean(x²) + ε) ──
        # pow(2)：逐元素平方
        # mean(-1, keepdim=True)：在最后一维（特征维）取均值，保持维度用于广播
        # rsqrt：倒数平方根（1/√x），即 1/RMS
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)

        # ── 还原精度 + 乘以可学习缩放参数 γ ──
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        # 调试时打印模块信息（如 print(model) 时显示）
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


# ══════════════════════════════════════════════════════════════════════════════
# Transformer 解码器单层
# ══════════════════════════════════════════════════════════════════════════════

class Qwen2DecoderLayer(GradientCheckpointingLayer):
    """
    单个 Transformer 解码器层（Pre-Norm 结构）。

    Pre-Norm 结构（本实现）：
        hidden = hidden + SelfAttn(RMSNorm(hidden))   # 先归一化，再注意力，再残差
        hidden = hidden + FFN(RMSNorm(hidden))         # 先归一化，再 FFN，再残差

    与 Post-Norm（原始 Transformer）的区别：
    - Post-Norm：hidden = RMSNorm(hidden + SelfAttn(hidden))
    - Pre-Norm 梯度更稳定，适合深层模型（28+ 层）的训练

    继承自 GradientCheckpointingLayer：
        支持梯度检查点（Gradient Checkpointing）——训练时不保存中间激活值，
        而是在反向传播时重新计算，以显存换计算，允许在有限 GPU 上训练更大的模型。
    """

    def __init__(self, config: Qwen2Config, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        # ── 自注意力子层 ──
        self.self_attn = Qwen2Attention(config=config, layer_idx=layer_idx)

        # ── 前馈网络子层（SwiGLU MLP）──
        self.mlp = Qwen2MLP(config)

        # ── 两个 RMSNorm 归一化层 ──
        # input_layernorm：注意力子层前的归一化（Pre-Norm）
        self.input_layernorm = Qwen2RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        # post_attention_layernorm：FFN 子层前的归一化（同样是 Pre-Norm）
        self.post_attention_layernorm = Qwen2RMSNorm(config.hidden_size, eps=config.rms_norm_eps)

        # 本层的注意力类型："full_attention" 或 "sliding_attention"
        self.attention_type = config.layer_types[layer_idx]

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        """
        单层前向传播（Pre-Norm 残差结构）。

        参数：
            hidden_states       : [batch, seq, hidden_size] 上一层输出
            attention_mask      : 因果掩码
            position_ids        : token 的位置索引（已废弃，由 cache_position 替代）
            past_key_values     : KV Cache
            use_cache           : 是否启用 KV Cache
            cache_position      : 当前 token 在序列中的绝对位置（用于 KV Cache 写入）
            position_embeddings : (cos, sin) 旋转位置编码，由外层统一计算后传入

        返回：
            hidden_states: [batch, seq, hidden_size] 本层处理后的输出
        """
        # ────────────────────────────────────
        # 第一个子层：自注意力（Self-Attention）
        # ────────────────────────────────────
        residual = hidden_states   # 保存残差连接的输入

        # Pre-Norm：先对输入归一化，再送入注意力层
        hidden_states = self.input_layernorm(hidden_states)

        # 计算自注意力（attn_weights 通常不使用，用 _ 忽略）
        hidden_states, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )

        # 残差连接：将注意力输出加回原始输入
        hidden_states = residual + hidden_states

        # ────────────────────────────────────
        # 第二个子层：前馈网络（FFN / MLP）
        # ────────────────────────────────────
        residual = hidden_states   # 保存残差连接的输入

        # Pre-Norm：先对注意力输出归一化，再送入 FFN
        hidden_states = self.post_attention_layernorm(hidden_states)

        # SwiGLU FFN 计算
        hidden_states = self.mlp(hidden_states)

        # 残差连接：将 FFN 输出加回注意力输出
        hidden_states = residual + hidden_states

        return hidden_states


# ══════════════════════════════════════════════════════════════════════════════
# 基础预训练模型（公共配置）
# ══════════════════════════════════════════════════════════════════════════════

@auto_docstring
class Qwen2PreTrainedModel(PreTrainedModel):
    """
    所有 Qwen2/ZLLM 模型类的公共基类。
    不包含任何模型权重，只定义通用的类属性。
    """
    config: Qwen2Config
    base_model_prefix = "model"        # 保存/加载权重时的前缀名

    supports_gradient_checkpointing = True  # 支持梯度检查点（节省训练显存）

    # 不应在设备间切分的模块（保证一个 Decoder 层始终在同一设备上）
    _no_split_modules = ["Qwen2DecoderLayer"]

    # KV Cache 张量的设备放置由 Cache 对象自行管理，不参与模型设备映射
    _skip_keys_device_placement = ["past_key_values"]

    # 支持的注意力后端
    _supports_flash_attn = True     # Flash Attention 2
    _supports_sdpa = True           # PyTorch SDPA（scaled dot product attention）
    _supports_flex_attn = True      # FlexAttention（PyTorch 2.5+）

    _can_compile_fullgraph = True   # 支持 torch.compile 全图编译优化
    _supports_attention_backend = True

    # 支持输出中间层隐藏状态和注意力权重（用于解释性分析）
    _can_record_outputs = {
        "hidden_states": Qwen2DecoderLayer,
        "attentions":    Qwen2Attention,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 旋转位置编码计算模块
# ══════════════════════════════════════════════════════════════════════════════

class Qwen2RotaryEmbedding(nn.Module):
    """
    旋转位置编码（RoPE）计算模块。

    RoPE 的核心：为每个维度分配一个不同频率的正弦波，
    通过频率差异实现不同维度对不同距离的位置敏感性。

    inv_freq（频率倒数）的计算公式：
        inv_freq[i] = 1 / (θ^(2i/d))   i = 0, 1, ..., d/2-1
    其中 θ = rope_theta（默认 10000），d = head_dim

    低频维度（小 i）：变化慢，捕捉长程位置关系
    高频维度（大 i）：变化快，捕捉短程位置关系

    forward 输出：
        cos, sin：shape [batch, seq, head_dim]
        直接传递给 apply_rotary_pos_emb 应用到 Q/K

    注意：该模块没有可训练参数（inv_freq 是确定性计算，只注册为 buffer）
    """
    inv_freq: torch.Tensor  # 类型注解，供 linting 工具识别 register_buffer 的属性

    def __init__(self, config: Qwen2Config, device=None):
        super().__init__()

        # 确定 RoPE 变体类型（default / linear / dynamic / yarn / longrope / llama3）
        # 向后兼容：旧版本用 "type" 字段
        if hasattr(config, "rope_scaling") and isinstance(config.rope_scaling, dict):
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"  # 标准 RoPE

        # 当前缓存的最大序列长度，超过时需要扩展 inv_freq
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings
        self.config = config

        # 根据 rope_type 选择对应的初始化函数（如动态 NTK 扩展、YaRN 等）
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        # 计算 inv_freq 和 attention_scaling（部分 RoPE 变体会调整注意力缩放）
        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)

        # register_buffer：将 inv_freq 注册为模型缓冲区（不是参数，但会随模型保存/移动设备）
        # persistent=False：不保存到 state_dict（可从 config 重新计算）
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq  # 保存原始值，动态 RoPE 扩展时可能临时修改

    @torch.no_grad()  # RoPE 计算不需要梯度
    @dynamic_rope_update  # 装饰器：推理时若序列超出缓存范围，自动扩展 inv_freq
    def forward(self, x, position_ids):
        """
        计算给定位置的 RoPE cos/sin 编码。

        参数：
            x           : 任意张量，仅用于获取 device 和 dtype 信息
            position_ids: [batch, seq] 每个 token 的位置索引

        返回：
            cos, sin: [batch, seq, head_dim]，后续传入 apply_rotary_pos_emb
        """
        # ── 构造频率矩阵 ──
        # inv_freq: [head_dim/2]
        # inv_freq_expanded: [batch, head_dim/2, 1]
        inv_freq_expanded = (
            self.inv_freq[None, :, None]
            .float()
            .expand(position_ids.shape[0], -1, 1)
            .to(x.device)
        )

        # position_ids_expanded: [batch, 1, seq]
        position_ids_expanded = position_ids[:, None, :].float()

        # 在 CPU 上强制 float32 精度计算（MPS 不支持 autocast，退回 CPU 精度）
        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):
            # freqs: [batch, head_dim/2, 1] × [batch, 1, seq] → [batch, seq, head_dim/2]
            # matmul 后 transpose：外积，得到每个位置×每个频率的相位角
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)

            # 在最后一维拼接两份 freqs，构造完整 head_dim 维度的角度
            # 这对应 RoPE 的"前半维度 cos，后半维度 sin"的设计
            emb = torch.cat((freqs, freqs), dim=-1)

            # attention_scaling：YaRN 等变体会调整注意力缩放，默认为 1.0
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        # 还原为输入张量的精度（float16 / bfloat16）
        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


# ══════════════════════════════════════════════════════════════════════════════
# 裸 Transformer 模型（无任务头）
# ══════════════════════════════════════════════════════════════════════════════

@auto_docstring
class Qwen2Model(Qwen2PreTrainedModel):
    """
    ZLLM / Qwen2 的裸模型主体，仅包含：
        embed_tokens  → N × Qwen2DecoderLayer → norm

    不包含任何任务头（如 lm_head），作为所有下游任务模型的主干网络。
    输出 last_hidden_state：[batch, seq, hidden_size]
    """

    def __init__(self, config: Qwen2Config):
        super().__init__(config)
        self.padding_idx = config.pad_token_id  # Padding token 的 ID（用于 Embedding 初始化）
        self.vocab_size = config.vocab_size

        # ── Token Embedding 层 ──
        # 将 token ID 映射为 hidden_size 维的稠密向量
        # padding_idx：该 ID 对应的 Embedding 向量始终为 0 且不更新梯度
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)

        # ── N 个解码器层 ──
        # 每层有独立的注意力、FFN 和归一化权重
        self.layers = nn.ModuleList(
            [Qwen2DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )

        # ── 最终归一化层 ──
        # 在所有解码器层之后，对最终 hidden_states 做 RMSNorm，
        # 稳定 lm_head 的输入分布
        self.norm = Qwen2RMSNorm(config.hidden_size, eps=config.rms_norm_eps)

        # ── 旋转位置编码模块 ──
        # 统一计算所有层共享的 cos/sin，避免每层重复计算
        self.rotary_emb = Qwen2RotaryEmbedding(config=config)

        self.gradient_checkpointing = False

        # 是否有使用滑动窗口的层（决定是否需要构造 sliding_attention 掩码）
        self.has_sliding_layers = "sliding_attention" in self.config.layer_types

        # 权重初始化 + 特殊处理（如 tie_word_embeddings）
        self.post_init()

    @check_model_inputs  # 校验输入格式，给出友好的错误提示
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,    # token ID 序列
        attention_mask: Optional[torch.Tensor] = None,   # 用户输入的 padding 掩码（1=有效，0=填充）
        position_ids: Optional[torch.LongTensor] = None, # 位置索引（通常自动推导）
        past_key_values: Optional[Cache] = None,         # KV Cache
        inputs_embeds: Optional[torch.FloatTensor] = None, # 直接传 Embedding（与 input_ids 二选一）
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        """
        模型前向传播（完整流程）。

        参数 input_ids 与 inputs_embeds 二选一：
        - 通常传 input_ids（token ID），模型内部查 embed_tokens 转换
        - 传 inputs_embeds 可跳过 Embedding 查表步骤（如 multimodal 场景）
        """

        # ── 互斥检验：input_ids 与 inputs_embeds 只能给一个 ──
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        # ── Token ID → Embedding 向量 ──
        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        # ── 初始化 KV Cache ──
        # 推理首步（past_key_values=None）时创建空的 DynamicCache
        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        # ── 计算 cache_position（当前步 token 在完整序列中的绝对位置）──
        # 续写推理时，past_seen_tokens > 0，cache_position 从上次结束的位置继续
        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens,
                past_seen_tokens + inputs_embeds.shape[1],
                device=inputs_embeds.device
            )

        # ── 计算 position_ids ──
        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)  # [1, seq]

        # ── 构造因果注意力掩码 ──
        # causal_mask_mapping 是一个字典，key 为注意力类型，value 为对应的掩码张量
        if not isinstance(causal_mask_mapping := attention_mask, dict):
            # attention_mask 不是字典说明还未处理，需要构造
            mask_kwargs = {
                "config":          self.config,
                "input_embeds":    inputs_embeds,
                "attention_mask":  attention_mask,   # 用户提供的 padding 掩码
                "cache_position":  cache_position,
                "past_key_values": past_key_values,
                "position_ids":    position_ids,
            }
            # 全注意力层的因果掩码（下三角矩阵 + padding 掩码合并）
            causal_mask_mapping = {
                "full_attention": create_causal_mask(**mask_kwargs),
            }
            # 滑动窗口注意力层额外需要带窗口限制的掩码
            if self.has_sliding_layers:
                causal_mask_mapping["sliding_attention"] = create_sliding_window_causal_mask(**mask_kwargs)

        # ── 初始化 hidden_states 为 token Embedding ──
        hidden_states = inputs_embeds

        # ── 统一计算 RoPE 位置编码（所有层共享）──
        # 避免每层重复计算，提升效率
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # ── 逐层通过 Decoder Layer ──
        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            # 根据本层的注意力类型选择对应的掩码
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask_mapping[decoder_layer.attention_type],
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )

        # ── 最终归一化 ──
        hidden_states = self.norm(hidden_states)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            # hidden_states / attentions 字段在需要时由 _can_record_outputs 机制填充
        )


# ══════════════════════════════════════════════════════════════════════════════
# 因果语言模型（CausalLM）—— 文本生成的主要入口
# ══════════════════════════════════════════════════════════════════════════════

@auto_docstring
class Qwen2ForCausalLM(Qwen2PreTrainedModel, GenerationMixin):
    """
    带语言模型头（lm_head）的因果语言模型。

    结构：Qwen2Model + lm_head（Linear: hidden_size → vocab_size）

    输出 logits：[batch, seq, vocab_size]
        每个位置对词表中每个 token 的未归一化得分（log-probability 的线性变换）
        推理时取最后一个位置的 logits，softmax 后采样得到下一个 token。

    继承 GenerationMixin 获得 .generate() 方法，支持：
        - 贪心解码（greedy decoding）
        - 束搜索（beam search）
        - 温度采样（temperature sampling）
        - Top-k / Top-p 采样
    """
    # lm_head.weight 与 embed_tokens.weight 可选绑定（由 tie_word_embeddings 控制）
    _tied_weights_keys = ["lm_head.weight"]

    # 张量并行：lm_head 按列切分（输出 logits 分布在多卡，最后 all-gather）
    _tp_plan = {"lm_head": "colwise_rep"}
    # 流水线并行：lm_head 的输入是 hidden_states，输出是 logits
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = Qwen2Model(config)          # 主干 Transformer 模型
        self.vocab_size = config.vocab_size
        # lm_head：将 hidden_size 维向量映射到词表大小，不带 bias
        # 输出即为每个 token 的 unnormalized log-probability（logits）
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self.post_init()

    @can_return_tuple  # 允许以元组形式返回输出（兼容旧版 API）
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,  # 训练时的目标 token ID
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,  # 只保留最后 N 个位置的 logits（推理优化）
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        """
        前向传播。

        logits_to_keep 参数：
            推理时通常只需要最后一个 token 的 logits 来决定下一个词，
            设置 logits_to_keep=1 可避免计算所有 seq_len 个 logits，节省显存和计算。
            训练时需要所有位置的 logits 计算 loss，设为 0（即保留全部）。

        labels 参数：
            传入时计算交叉熵 loss（训练用）。
            labels 通常是 input_ids 左移一位（即预测下一个 token）。
            padding 位置的 label 设为 -100，loss_function 会自动忽略。
        """
        # ── 主干模型前向传播 ──
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state  # [batch, seq, hidden_size]

        # ── 按需计算 logits（推理优化）──
        # logits_to_keep=1：只取最后 1 个位置的 logits，显存友好
        # logits_to_keep=0：取全部位置（等价于 slice(-0, None) = 全部）
        # logits_to_keep 也可以是 tensor（指定具体位置索引，用于 speculative decoding）
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        # ── 计算损失（仅训练时）──
        loss = None
        if labels is not None:
            # loss_function 由基类实现，默认为 CrossEntropyLoss
            # 自动处理 vocab_size 维度的 softmax + 负对数似然
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,                          # [batch, seq(or 1), vocab_size]
            past_key_values=outputs.past_key_values, # 更新后的 KV Cache
            hidden_states=outputs.hidden_states,     # 各层中间状态（需配置才输出）
            attentions=outputs.attentions,           # 各层注意力权重（需配置才输出）
        )


# ══════════════════════════════════════════════════════════════════════════════
# 下游任务头（直接复用 Generic 实现）
# ══════════════════════════════════════════════════════════════════════════════

class Qwen2ForSequenceClassification(GenericForSequenceClassification, Qwen2PreTrainedModel):
    """
    序列分类模型（如情感分析、意图识别）。
    在 [CLS] 位置（通常是最后一个非 padding token）的 hidden_state 上接分类头。
    完全复用 GenericForSequenceClassification 的 forward 逻辑，无需额外实现。
    """
    pass


class Qwen2ForTokenClassification(GenericForTokenClassification, Qwen2PreTrainedModel):
    """
    Token 级别分类模型（如命名实体识别 NER）。
    对每个 token 的 hidden_state 独立做分类，输出 [batch, seq, num_labels]。
    """
    pass


class Qwen2ForQuestionAnswering(GenericForQuestionAnswering, Qwen2PreTrainedModel):
    """
    抽取式问答模型（如 SQuAD）。
    预测答案在原文中的起始和结束位置（start_logits / end_logits）。
    base_model_prefix 设为 "transformer" 是为了兼容部分旧版 checkpoint 的权重键名。
    """
    base_model_prefix = "transformer"  # 历史兼容：旧版本用 "transformer" 而非 "model"


# 对外导出的公开类列表
__all__ = [
    "Qwen2PreTrainedModel",
    "Qwen2Model",
    "Qwen2ForCausalLM",
    "Qwen2RMSNorm",
    "Qwen2ForSequenceClassification",
    "Qwen2ForTokenClassification",
    "Qwen2ForQuestionAnswering",
]
